fixtures:
  repositories:
    "repos": "git://github.com/jmslagle/puppet-jslagle-repos.git"
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "puppet": "#{source_dir}"
